"""Change note to content

Revision ID: 541d967cb1b0
Revises: d4e527747e32
Create Date: 2022-06-01 03:10:14.015603

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '541d967cb1b0'
down_revision = 'd4e527747e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('note', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('note', mysql.TEXT(), nullable=False))
    op.drop_column('note', 'content')
    # ### end Alembic commands ###
