"""Added user to notes

Revision ID: d4e527747e32
Revises: 73decf30ec5d
Create Date: 2022-05-31 17:32:49.774499

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'd4e527747e32'
down_revision = '73decf30ec5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'user_id')
    # ### end Alembic commands ###
