"""removed unique title

Revision ID: f3a14e046db9
Revises: 541d967cb1b0
Create Date: 2022-06-02 16:07:05.460511

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'f3a14e046db9'
down_revision = '541d967cb1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'note', ['title'], unique=False)
    # ### end Alembic commands ###
